name: Posts
markdown: kramdown
pygments: true
safe: true
url: http://paanini.github.io
titlecase: true
author: Paanini
email: hello@paanini.me
root: /
permalink: /:title/

prose:
  
  metadata:
    "_posts":
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "hidden"
          value: "Title"
      - name: "comments"
        field:
          label: "Allow comments"
          element: "checkbox"
          value: true
      - name: "categories"
        field:
          element: "text"
          value: "misc"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
